# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc files/fpga_k35.xdc

# XDC: imports/xdc files/boot.xdc

# TCL: imports/xdc files/axis_async_fifo.tcl

# TCL: imports/xdc files/eth_xcvr_phy_10g_gty_wrapper.tcl

# TCL: imports/xdc files/mqnic_port.tcl

# TCL: imports/xdc files/mqnic_ptp_clock.tcl

# TCL: imports/xdc files/mqnic_rb_clk_info.tcl

# TCL: imports/xdc files/ptp_td_leaf.tcl

# TCL: imports/xdc files/rb_drp.tcl

# TCL: imports/xdc files/sync_reset.tcl

# TCL: imports/xdc files/tdma_ber_ch.tcl

# IP: ip/eth_xcvr_gth_channel/eth_xcvr_gth_channel.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth_xcvr_gth_channel || ORIG_REF_NAME==eth_xcvr_gth_channel} -quiet] -quiet

# IP: ip/eth_xcvr_gth_full/eth_xcvr_gth_full.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth_xcvr_gth_full || ORIG_REF_NAME==eth_xcvr_gth_full} -quiet] -quiet
