# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku035-fbva676-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.cache/wt [current_project]
set_property parent.project_path /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property generic {FPGA_ID=32'h03823093 FW_ID=32'h00000000 FW_VER=32'h00000100 BOARD_ID=32'h1ce40003 BOARD_VER=32'h01000000 BUILD_DATE=32'd1762433129 GIT_HASH=32'h00000000 RELEASE_INFO=32'h00000000 TDMA_BER_ENABLE=0 IF_COUNT=2 PORTS_PER_IF=1 SCHED_PER_IF=1 PORT_MASK=0 CLK_PERIOD_NS_NUM=4 CLK_PERIOD_NS_DENOM=1 PTP_CLOCK_PIPELINE=0 PTP_CLOCK_CDC_PIPELINE=0 PTP_PORT_CDC_PIPELINE=0 PTP_PEROUT_ENABLE=1 PTP_PEROUT_COUNT=1 EVENT_QUEUE_OP_TABLE_SIZE=32 TX_QUEUE_OP_TABLE_SIZE=32 RX_QUEUE_OP_TABLE_SIZE=32 CQ_OP_TABLE_SIZE=32 EQN_WIDTH=5 TX_QUEUE_INDEX_WIDTH=11 RX_QUEUE_INDEX_WIDTH=8 CQN_WIDTH=12 EQ_PIPELINE=3 TX_QUEUE_PIPELINE=3 RX_QUEUE_PIPELINE=3 CQ_PIPELINE=3 TX_DESC_TABLE_SIZE=32 RX_DESC_TABLE_SIZE=32 RX_INDIR_TBL_ADDR_WIDTH=8 TX_SCHEDULER_OP_TABLE_SIZE=32 TX_SCHEDULER_PIPELINE=3 TDMA_INDEX_WIDTH=6 PTP_TS_ENABLE=1 TX_CPL_FIFO_DEPTH=32 TX_CHECKSUM_ENABLE=1 RX_HASH_ENABLE=1 RX_CHECKSUM_ENABLE=1 PFC_ENABLE=1 LFC_ENABLE=1 ENABLE_PADDING=1 ENABLE_DIC=1 MIN_FRAME_LENGTH=64 TX_FIFO_DEPTH=32768 RX_FIFO_DEPTH=65536 MAX_TX_SIZE=9214 MAX_RX_SIZE=9214 TX_RAM_SIZE=32768 RX_RAM_SIZE=32768 APP_ID=32'h00000000 APP_ENABLE=0 APP_CTRL_ENABLE=1 APP_DMA_ENABLE=1 APP_AXIS_DIRECT_ENABLE=1 APP_AXIS_SYNC_ENABLE=1 APP_AXIS_IF_ENABLE=1 APP_STAT_ENABLE=1 DMA_IMM_ENABLE=0 DMA_IMM_WIDTH=32 DMA_LEN_WIDTH=16 DMA_TAG_WIDTH=16 RAM_ADDR_WIDTH=15 RAM_PIPELINE=2 IRQ_INDEX_WIDTH=5 AXIL_CTRL_DATA_WIDTH=32 AXIL_CTRL_ADDR_WIDTH=24 AXIL_APP_CTRL_DATA_WIDTH=32 AXIL_APP_CTRL_ADDR_WIDTH=24 AXIS_ETH_TX_PIPELINE=0 AXIS_ETH_TX_FIFO_PIPELINE=2 AXIS_ETH_TX_TS_PIPELINE=0 AXIS_ETH_RX_PIPELINE=0 AXIS_ETH_RX_FIFO_PIPELINE=2 STAT_ENABLE=1 STAT_DMA_ENABLE=1 STAT_PCIE_ENABLE=1 STAT_INC_WIDTH=24 STAT_ID_WIDTH=10 AXIS_PCIE_DATA_WIDTH=256} [current_fileset]
read_verilog -library xil_defaultlib {
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/arbiter.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_crossbar.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_crossbar_addr.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_crossbar_rd.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_crossbar_wr.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_interconnect.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_ram.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_reg_if.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_reg_if_rd.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_reg_if_wr.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_register_rd.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axil_register_wr.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_adapter.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_arb_mux.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_async_fifo.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_async_fifo_adapter.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_demux.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_fifo.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_fifo_adapter.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_pipeline_fifo.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_xgmii_rx_32.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_xgmii_rx_64.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_xgmii_tx_32.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/axis_xgmii_tx_64.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/cpl_op_mux.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/cpl_queue_manager.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/cpl_write.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/desc_fetch.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/desc_op_mux.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_client_axis_sink.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_client_axis_source.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_if_desc_mux.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_if_mux.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_if_mux_rd.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_if_mux_wr.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_if_pcie.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_if_pcie_rd.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_if_pcie_wr.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_psdpram.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_ram_demux_rd.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/dma_ram_demux_wr.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_mac_10g.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_phy_10g.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_phy_10g_rx.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_phy_10g_rx_ber_mon.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_phy_10g_rx_frame_sync.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_phy_10g_rx_if.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_phy_10g_rx_watchdog.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_phy_10g_tx.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_phy_10g_tx_if.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_xcvr_phy_10g_gty_quad_wrapper.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/eth_xcvr_phy_10g_gty_wrapper.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/fpga_core.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/i2c_single_reg.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/irq_rate_limit.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/lfsr.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mac_ctrl_rx.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mac_ctrl_tx.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mac_pause_ctrl_rx.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mac_pause_ctrl_tx.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_app_block.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_core.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_core_pcie.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_core_pcie_us.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_dram_if.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_egress.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_ingress.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_interface.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_interface_rx.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_interface_tx.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_l2_egress.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_l2_ingress.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_port.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_port_map_phy_xgmii.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_port_rx.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_port_tx.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_ptp.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_ptp_clock.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_ptp_perout.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_rb_clk_info.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_rx_queue_map.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/mqnic_tx_scheduler_block_rr.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_axil_master.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_msix.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_tlp_demux_bar.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_tlp_fifo.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_tlp_fifo_raw.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_tlp_mux.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_us_cfg.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_us_if.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_us_if_cc.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_us_if_cq.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_us_if_rc.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_us_if_rq.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pcie_us_msi.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/priority_encoder.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/ptp_perout.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/ptp_td_leaf.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/ptp_td_phc.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/pulse_merge.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/queue_manager.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/rb_drp.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/rx_checksum.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/rx_engine.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/rx_fifo.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/rx_hash.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/stats_collect.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/stats_counter.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/stats_dma_if_pcie.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/stats_dma_latency.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/stats_pcie_if.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/stats_pcie_tlp.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/sync_reset.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/sync_signal.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/tdma_ber.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/tdma_ber_ch.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/tdma_scheduler.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/tx_checksum.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/tx_engine.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/tx_fifo.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/tx_req_mux.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/tx_scheduler_rr.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/xgmii_baser_dec_64.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/xgmii_baser_enc_64.v
  /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/imports/source/fpga_k35.v
}
read_ip -quiet /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_channel/eth_xcvr_gth_channel.xci
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_channel/synth/eth_xcvr_gth_channel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_channel/synth/eth_xcvr_gth_channel.xdc]

read_ip -quiet /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_full/eth_xcvr_gth_full.xci
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_full/synth/eth_xcvr_gth_full_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_full/synth/eth_xcvr_gth_full.xdc]

read_ip -quiet /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/pcie3_ultrascale_0/pcie3_ultrascale_0.xci
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/pcie3_ultrascale_0/ip_0/synth/pcie3_ultrascale_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/pcie3_ultrascale_0/ip_0/synth/pcie3_ultrascale_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/pcie3_ultrascale_0/source/pcie3_ultrascale_0-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/sources_1/ip/pcie3_ultrascale_0/synth/pcie3_ultrascale_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/fpga_k35.xdc}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/fpga_k35.xdc}}]

read_xdc {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/boot.xdc}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/boot.xdc}}]

read_xdc -unmanaged {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/axis_async_fifo.tcl}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/axis_async_fifo.tcl}}]

read_xdc -unmanaged {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/eth_xcvr_phy_10g_gty_wrapper.tcl}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/eth_xcvr_phy_10g_gty_wrapper.tcl}}]

read_xdc -unmanaged {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/mqnic_port.tcl}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/mqnic_port.tcl}}]

read_xdc -unmanaged {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/mqnic_ptp_clock.tcl}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/mqnic_ptp_clock.tcl}}]

read_xdc -unmanaged {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/mqnic_rb_clk_info.tcl}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/mqnic_rb_clk_info.tcl}}]

read_xdc -unmanaged {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/ptp_td_leaf.tcl}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/ptp_td_leaf.tcl}}]

read_xdc -unmanaged {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/rb_drp.tcl}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/rb_drp.tcl}}]

read_xdc -unmanaged {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/sync_reset.tcl}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/sync_reset.tcl}}]

read_xdc -unmanaged {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/tdma_ber_ch.tcl}}
set_property used_in_implementation false [get_files {{/home/chenxun/Documents/Project/corundum_with_host/src_Vivado/project_1.srcs/constrs_1/imports/xdc files/tdma_ber_ch.tcl}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fpga -part xcku035-fbva676-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_utilization_synth.rpt -pb fpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
