# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chenxun/Documents/Project/corundum_exanic_x10/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_full/eth_xcvr_gth_full.xci
# IP: The module: 'eth_xcvr_gth_full' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chenxun/Documents/Project/corundum_exanic_x10/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_full/synth/eth_xcvr_gth_full_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_xcvr_gth_full'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chenxun/Documents/Project/corundum_exanic_x10/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_full/synth/eth_xcvr_gth_full.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_xcvr_gth_full'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/chenxun/Documents/Project/corundum_exanic_x10/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_full/eth_xcvr_gth_full.xci
# IP: The module: 'eth_xcvr_gth_full' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chenxun/Documents/Project/corundum_exanic_x10/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_full/synth/eth_xcvr_gth_full_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_xcvr_gth_full'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chenxun/Documents/Project/corundum_exanic_x10/src_Vivado/project_1.srcs/sources_1/ip/eth_xcvr_gth_full/synth/eth_xcvr_gth_full.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_xcvr_gth_full'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
